spring:
#    datasource:
#        driver-class-name: org.h2.Driver
#        username: sa
#        password:
#        url: jdbc:h2:mem:querydsl
    jpa:
#        hibernate:
#            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        org.hibernate.SQL: debug